[general]
output_path = "~/.config/niri/config.kdl"

[genconfig]
sources = [
  "$XDG_CONFIG_HOME/niri/src/internal.kdl",
  "$XDG_CONFIG_HOME/niri/src/monitors.kdl",
  "$XDG_CONFIG_HOME/niri/src/input.kdl",
  "$XDG_CONFIG_HOME/niri/src/keybindings.kdl",
  "$XDG_CONFIG_HOME/niri/src/visual.kdl",
  "$XDG_CONFIG_HOME/niri/src/rules.kdl",
]

[workspaces]
dmenu_command = "rofi -dmenu -theme ~/.local/share/rofi/themes/basic_launcher/rounded_with_listview.rasi -p '󰾂   workspace'"
task_delay = 0.6

[workspaces.items]
"leetcoding" = [
  { workspace = 1, run = 'footclient -e fish -c "nvim; fish"' },
  { workspace = 1, run = "brave --new-window https://leetcode.com/ https://neetcode.io/" },
]
